name: Update Leetcode Cookies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */14 * *" # Run every 2 weeks

jobs:
  update_cookies:
    runs-on: ubuntu-latest

    env:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      leetcode-email: ${{ secrets.LEETCODE_EMAIL }}
      leetcode-password: ${{ secrets.LEETCODE_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: pre-installations
        run: npx puppeteer browsers install chrome

      - name: Fetch LeetCode cookies
        run: node fetchLeetCodeCookies.js