name: Update Leetcode Cookies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */14 * *" # Run every 2 weeks

jobs:
  update_cookies:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-email: ${{ secrets.LEETCODE_EMAIL }}
          leetcode-password: ${{ secrets.LEETCODE_PASSWORD }}

      - name: Install dependencies
        run: npm ci

      - name: Fetch LeetCode cookies
        run: node fetchLeetCodeCookies.js